name: Bar Jolly Roger
favicon: null
layout_spectrum: 0.6936050660442561
typography_spectrum: 0.47362641617655754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#980300'
    - '#d0e25c'
    - '#623000'
    - '#c03f00'
    - '#979000'
  brandStrength: 0.6069494998082519
  lightness: 0.908440119586885
  saturation: 0.9472900396212935
  rhythmicContrast: 0.9168709374498576
purpose: []
