name: Bar Jolly Roger
favicon: null
layout_spectrum: 0.98435
typography_spectrum: 0.10773
title: Hot Wings. Cold Beer.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#980300'
    - '#d0e25c'
    - '#623000'
    - '#c03f00'
    - '#979000'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
